UPDATE public.site_items
SET data = CASE data->>'image'
  WHEN '/media/rose-sweet-slices.jpg' THEN jsonb_build_object('title','Rose Kesar Dry Fruit Mithai','local','गुलाब केसर ड्राई फ्रूट मिठाई','category','Artisanal Mithai','description','Rose-coated dry-fruit mithai with a bright kesar centre, arranged around a handcrafted sugar rose.','tags','Pure Desi Ghee, Chef Signature','pairing','Masala chai, kahwa or rose milk.','image','/media/rose-sweet-slices.jpg')
  WHEN '/media/rose-sweet-cups-2.jpg' THEN jsonb_build_object('title','Rose Mawa Cups','local','गुलाब मावा कप','category','Artisanal Mithai','description','Golden mawa cups crowned with rose-flavoured mithai and finished for wedding service.','tags','Pure Desi Ghee, Chef Signature','pairing','Kesar milk or masala chai.','image','/media/rose-sweet-cups-2.jpg')
  WHEN '/media/shadi-breakfast.jpg' THEN jsonb_build_object('title','Wedding Breakfast Platter','local','शादी का नाश्ता','category','Multi-Cuisine Banquets','description','A wedding breakfast plate with sandwiches, savoury bites, chaat and fresh accompaniments.','tags','Wedding Breakfast, Jain Available','pairing','Tea, coffee or fresh juice.','image','/media/shadi-breakfast.jpg')
  WHEN '/media/haldi-breakfast.jpg' THEN jsonb_build_object('title','Haldi Breakfast Platter','local','हल्दी का नाश्ता','category','Multi-Cuisine Banquets','description','A festive breakfast plate with savoury pancakes, dhokla, jalebi and colourful garnishes.','tags','Breakfast Service, Jain Available','pairing','Masala chai or fresh juice.','image','/media/haldi-breakfast.jpg')
  WHEN '/media/mehendi-lunch.jpg' THEN jsonb_build_object('title','Mehendi Lunch Thali','local','मेहंदी लंच थाली','category','Royal Rajasthani Thaal','description','A generous lunch thali with roti, rice, curries and traditional accompaniments.','tags','Wedding Lunch, Heritage Service','pairing','Chaas, salad and seasonal pickle.','image','/media/mehendi-lunch.jpg')
  WHEN '/media/haldi-dinner.jpg' THEN jsonb_build_object('title','Haldi Dinner Thali','local','हल्दी डिनर थाली','category','Royal Rajasthani Thaal','description','A complete celebration thali with rice, dal, kadhi, vegetables, breads and sweets.','tags','Wedding Dinner, Jain Available','pairing','Chaas and fresh salad.','image','/media/haldi-dinner.jpg')
  WHEN '/media/live-dosa-counter.jpg' THEN jsonb_build_object('title','Live Moong Chilla Counter','local','लाइव मूंग चीला काउंटर','category','Live Theatrical Counters','description','Fresh moong chillas cooked and garnished live for guests at the celebration.','tags','Live Counter, Made to Order','pairing','Green chutney and house masala.','image','/media/live-dosa-counter.jpg')
  WHEN '/media/high-tea.jpg' THEN jsonb_build_object('title','Masala Maggi','local','मसाला मैगी','category','Live Theatrical Counters','description','Hot masala Maggi tossed with vegetables and served fresh at the live counter.','tags','Live Counter, Jain Available','pairing','Tea, coffee or chilled refreshments.','image','/media/high-tea.jpg')
  ELSE data
END
WHERE kind = 'dish'
  AND data->>'image' IN ('/media/rose-sweet-slices.jpg','/media/rose-sweet-cups-2.jpg','/media/shadi-breakfast.jpg','/media/haldi-breakfast.jpg','/media/mehendi-lunch.jpg','/media/haldi-dinner.jpg','/media/live-dosa-counter.jpg','/media/high-tea.jpg');